### ISSUE TITLE
Empty href in feed.njk

### ISSUE THREAD

**Issue by yellowled** [maxboeck/eleventastic#1]
Both "top-level" `<link>` elements in `src/feed.njk` produce empty `href` attributes, most likely a result of copypasting templates from other projects which used different data files. [Both](https://github.com/maxboeck/eleventastic/blob/master/src/feed.njk#L9-L10) use `{{ site.url }}`, which should be `{{ meta.url }}`, I assume.

Since you don't have contributing guidelines, I wasn't sure if you were accepting PRs, but still wanted to report this.

Thank you for creating eleventastic, I learned a lot from it. :)

**Comment by maxboeck** [comment]
you're absolutely correct, that was a copy-pasting error.
thanks so much for noticing! 🙌
