### ISSUE TITLE
Enhancement: Improve SVG Sprite compile time

### ISSUE THREAD

**Issue by patrickxchong** [maxboeck/eleventastic#17]
Hi @maxboeck, first off, thank you for creating this template! It's been very helpful to kickstart my Eleventy journey. Would like to make a performance improvement suggestion:

The current iconsprite shortcode compiles an svg sprite each time a page is rendered, which leads to slow rebuilds in development. I managed to come up with a solution that compiles the svgsprite in 11ty's beforeBuild hook and only recompiles when a file is added/changed to the svg directory. I encapsulated the solution into a plugin for easy setup (https://github.com/patrickxchong/eleventy-plugin-svg-sprite), and it can work as drop in replacement for what you have here with the right configuration options. 

Would you be open to the idea of incorporating this plugin into this template? I would be happy to make a PR for this.

**Comment by maxboeck** [comment]
closing this, since we incorporated the plugin.
