### ISSUE TITLE
Build timestamp in base.njk causes longer build and deploy times on Netlify

### ISSUE THREAD

**Issue by freshyill** [maxboeck/eleventastic#3]
I recently incorporated much of Eleventastic into an under-the-hood update of my own Eleventy site, and I noticed that build times increased quite a bit. It looks like the build time included in base.njk leads to much longer build and deploy times on Netlify since this triggers a change in _every_ page that relies on base.njk.

According to [this Netlify support doc](https://community.netlify.com/t/support-guide-making-the-most-of-netlifys-cdn-cache/127), this invalidates every page in their CDN cache. I noticed an increase from 2–3 minute builds before Elventastic to 4–5 minute builds with it. Removing this from base.njk dropped build times back down to 2–3 minutes.

I like the idea of being able to check build times so my solution was to create a build.njk page that generates out a single page with the same information. Would you consider making a similar change to the project?

**Comment by maxboeck** [comment]
oh wow, I was unaware of that. that is indeed quite a difference at scale!
I've taken your advice and moved the build timestamp to a standalone `build.txt` info file.
Excluded it from sitemaps and crawling.

thanks for the hint! 🙌
