### ISSUE TITLE
permalink: false breaks navigation.njk

### ISSUE THREAD

**Issue by freshyill** [maxboeck/eleventastic#9]
Hi Max,

I came across an issue with in navigation.njk: If you have `permalink: false` set on any page, it breaks with a type error on line 22

https://github.com/maxboeck/eleventastic/blob/59f0c4f9f5a7e3b6e4b0569c1097f1265b87d7a9/src/includes/navigation.njk#L22

Sorry I have no time to propose a fix or submit a PR!

**Comment by maxboeck** [comment]
Thanks for the heads up - was busy with work the last month(s) but will have a look soon! 👍

**Comment by maxboeck** [comment]
should be fixed now!
